### ISSUE TITLE
how to return just 2 or more fields

### ISSUE THREAD

**Issue by specie** [danitseitlin/redis-modules-sdk#68] opened 2021-03-31 23:35 UTC
```
          return: {
            num: 1,
            field: 'tenant'
          }
```
is working but if I want more than one field:
```
          return: {
            num: 2,
            field: 'tenant _id'
          }
```
throws an error

**Comment by danitseitlin** [comment] 2021-04-03 17:51
@specie Hi there, sorry for the long wait (was on vacation).
I will take a look into the subject tomorrow evening

**Comment by danitseitlin** [comment] 2021-04-04 17:57
@specie So I could better understand, can you please send me the command you're trying to achieve?

**Comment by specie** [comment] 2021-04-05 13:41
> @specie So I could better understand, can you please share the command you're trying to achieve?

Hi Dani, this is the code I'm running

```
        const res = await rs.search('idx:v', '@tenant:{ACME} @state:{free} @location:[-31.50442215465239, -68.53204536191498 2000 m]', {
          limit: {
            first: 0,
            num: 1
          },
          return: {
            num: 2,
            **field: 'vehicle state'** <--- this seems to be the problem
          }
        })
```

Error: Redisearch: ReplyError: Unknown argument `0` at position 5 for <main>
    at Redisearch.handleError (/home/fabio/Documents/src/tests/redis_node/node_modules/redis-modules-sdk/lib/modules/module.base.js:50:19)
    at Redisearch.<anonymous> (/home/fabio/Documents/src/tests/redis_node/node_modules/redis-modules-sdk/lib/modules/redisearch.js:187:29)
    at Generator.throw (<anonymous>)
    at rejected (/home/fabio/Documents/src/tests/redis_node/node_modules/redis-modules-sdk/lib/modules/redisearch.js:6:65)

**Comment by danitseitlin** [comment] 2021-04-05 17:01
@specie Please install ver 0.4.6 which should contain a fix for this matter. I've made fields a string array and not a string. let me know if this doesn't work.

**Comment by specie** [comment] 2021-04-05 21:39
Still getting error:

Error: Redisearch: ReplyError: Unknown argument `0` at position 5 for <main>
    at Redisearch.handleError (/home/fabio/Documents/src/tests/redis_node/node_modules/redis-modules-sdk/lib/modules/module.base.js:50:19)
    at Redisearch.<anonymous> (/home/fabio/Documents/src/tests/redis_node/node_modules/redis-modules-sdk/lib/modules/redisearch.js:187:29)
    at Generator.throw (<anonymous>)
    at rejected (/home/fabio/Documents/src/tests/redis_node/node_modules/redis-modules-sdk/lib/modules/redisearch.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

The query I'm running in RedisInsight is this:

"@tenant:{ACME} @state:{free} @location:[-31.50442215465239, -68.53204536191498 2000 m]" return 2 vehicle state limit 0 1

**Comment by danitseitlin** [comment] 2021-04-05 22:16
@specie 
Hi, Can you give me your setup? want to have the exact same key as you.
In addition, i'd try:
```
const res = await client.search(index, '"@tenant:{ACME} @state:{free} @location:[-31.50442215465239, -68.53204536191498 2000 m]"', {
            limit: {
              first: 0,
              num: 1
            },
            return: {
              num: 2,
              fields: ['vehicle','state'] // this space separated value seems to be the problem
            }
          })
```
While the query has extra `"`. That might cause some issues in execution.

**Comment by danitseitlin** [comment] 2021-04-08 17:44
@specie Any update?

**Comment by danitseitlin** [comment] 2021-04-12 18:40
Closing this because I didn't hear back for a week. Sounds like maybe the issue is no longer a problem.

**Closed by danitseitlin** 2021-04-12 18:40 UTC
